# NUMPY Lesson 1

In [4]:
import numpy as np

In [5]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = np.mean(a, 0)

In [8]:
mean_a

array([2. , 8.4])

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
c = a[:,0]
d = a[:,1]

In [11]:
d

array([ 6,  8, 11, 10,  7])

In [12]:
c

array([1, 2, 3, 3, 1])

In [14]:
a_centered_sp = c @ d

In [15]:
a_centered_sp

92

In [16]:
rows, columns = a.shape
rows

5

In [17]:
a_centered_sp_dev = a_centered_sp / (rows - 1)
a_centered_sp_dev

23.0

# PANDAS Lesson 1

In [18]:
import pandas as pd

In [19]:
a = [1, 5, 3]

In [20]:
b = pd.Series(a)
b

0    1
1    5
2    3
dtype: int64

In [21]:
authors = {"author_id" : [1, 2, 3],
          "author_name" : ['Тургенев', 'Чехов', 'Островский']}

In [22]:
pd.DataFrame(authors)

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [23]:
book = {"author_id" : [1, 1, 1, 2, 2, 3, 3],
       "book_title" : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
       "price" : [450, 300, 350, 500, 450, 370, 290] }
pd.DataFrame(book)

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [47]:
authors_price = pd.merge(pd.DataFrame(authors), pd.DataFrame(book), on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [26]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [36]:
top5.sort_values('price', ascending=False)

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [104]:
authors_stat = authors_price.groupby('author_name').agg({'price':[('max_price','max'),('min_price','min'),('mean_price','mean')]})
#authors_stat = authors_stat.reset_index()
#authors_stat = authors_stat.rename(columns={'price':'max_price'})
pd.DataFrame(authors_stat)

price                      
            max_price min_price  mean_price
author_name                                
Островский        370       290  330.000000
Тургенев          450       300  366.666667
Чехов             500       450  475.000000